version: '3.7'
services:
  sample:
    container_name: reactdockerapp
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - '/app/node_modules'
    ports:
      - '3000:3000'
