version: '3.7'
services:
  sample:
    container_name: reactdockerapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development

